version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a week (on Monday)
    schedule:
      interval: "weekly"
      day: "monday"
    # Group all minor and patch updates together
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
    # Set reviewers for pull requests
    reviewers:
      - "zillyzoo-team"
    # Labels to apply to pull requests
    labels:
      - "dependencies"
      - "dependabot"
    # Specify the version update strategy
    versioning-strategy: "auto"
    # Set pull request limits
    open-pull-requests-limit: 10
    # Configure security updates
    security-updates-only: false
    # Ignore certain dependencies or versions
    ignore:
      # Ignore major updates for react packages until we're ready to migrate
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
    # Configure commit message settings
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
    reviewers:
      - "zillyzoo-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope" 